#+BEGIN_COMMENT
.. title: Embedding Bokeh
.. slug: embedding-bokeh
.. date: 2024-03-26 17:03:38 UTC-07:00
.. tags: experiment,bokeh,holoviews,hvplot
.. category: bokeh
.. link: 
.. description: Experimenting with embedding bokeh plots.
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 3
#+PROPERTY: header-args :session ~/.local/share/jupyter/runtime/kernel-5e9f25eb-f65d-4208-9a9f-33f71e43652d-ssh.json

#+BEGIN_SRC python :results none :exports none
%load_ext autoreload
%autoreload 2
#+END_SRC

* Standalone HTML Pages

First, the example from bokeh's documentation on [[https://docs.bokeh.org/en/latest/docs/user_guide/output/embed.html#html-files][creating standalone HTML files]].

** Imports and Setup

#+begin_src python :results none
# pypi
from bokeh.plotting import figure
from bokeh.resources import CDN
from bokeh.embed import file_html
#+end_src

The [[https://docs.bokeh.org/en/latest/docs/reference/embed.html#bokeh.embed.file_html][~file_html~]] function will create the text for a standalone HTML file to show a bokeh figure. If you just want to save the file they have a function called [[https://docs.bokeh.org/en/latest/docs/reference/io.html#bokeh.io.save][save]].

#+begin_src python :results none
def objectify(html: str) -> None:
    """print html in object tags"""
    print('<object type="text/html">')
    print(html)
    print('</object>')
    return
#+end_src

#+begin_src python output :exports both
plot = figure()
plot.circle([1, 2], [3, 4])
html = file_html(models=plot, resources=CDN, title="Full HTML")
objectify(html)
#+end_src

#+begin_export html
<object type="text/html">
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Full HTML</title>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.3.min.js"></script>
    <script type="text/javascript">
        Bokeh.set_log_level("info");
    </script>
  </head>
  <body>
    <div class="bk-root" id="8c42557a-d72a-448d-8f4a-9f4cc7c0323b" data-root-id="1183"></div>
  
    <script type="application/json" id="1363">
      {"942b8d57-0079-4937-aaed-1fe8d4555acd":{"defs":[],"roots":{"references":[{"attributes":{},"id":"1193","type":"BasicTicker"},{"attributes":{},"id":"1226","type":"BasicTickFormatter"},{"attributes":{"axis":{"id":"1192"},"coordinates":null,"group":null,"ticker":null},"id":"1195","type":"Grid"},{"attributes":{"bottom_units":"screen","coordinates":null,"fill_alpha":0.5,"fill_color":"lightgrey","group":null,"left_units":"screen","level":"overlay","line_alpha":1.0,"line_color":"black","line_dash":[4,4],"line_width":2,"right_units":"screen","syncable":false,"top_units":"screen"},"id":"1206","type":"BoxAnnotation"},{"attributes":{},"id":"1223","type":"BasicTickFormatter"},{"attributes":{"tools":[{"id":"1200"},{"id":"1201"},{"id":"1202"},{"id":"1203"},{"id":"1204"},{"id":"1205"}]},"id":"1207","type":"Toolbar"},{"attributes":{},"id":"1197","type":"BasicTicker"},{"attributes":{},"id":"1201","type":"WheelZoomTool"},{"attributes":{"data":{"x":[1,2],"y":[3,4]},"selected":{"id":"1229"},"selection_policy":{"id":"1228"}},"id":"1214","type":"ColumnDataSource"},{"attributes":{"coordinates":null,"data_source":{"id":"1214"},"glyph":{"id":"1215"},"group":null,"hover_glyph":null,"muted_glyph":{"id":"1217"},"nonselection_glyph":{"id":"1216"},"view":{"id":"1219"}},"id":"1218","type":"GlyphRenderer"},{"attributes":{"fill_color":{"value":"#1f77b4"},"line_color":{"value":"#1f77b4"},"x":{"field":"x"},"y":{"field":"y"}},"id":"1215","type":"Circle"},{"attributes":{},"id":"1229","type":"Selection"},{"attributes":{"fill_alpha":{"value":0.2},"fill_color":{"value":"#1f77b4"},"hatch_alpha":{"value":0.2},"line_alpha":{"value":0.2},"line_color":{"value":"#1f77b4"},"x":{"field":"x"},"y":{"field":"y"}},"id":"1217","type":"Circle"},{"attributes":{"axis":{"id":"1196"},"coordinates":null,"dimension":1,"group":null,"ticker":null},"id":"1199","type":"Grid"},{"attributes":{},"id":"1184","type":"DataRange1d"},{"attributes":{"fill_alpha":{"value":0.1},"fill_color":{"value":"#1f77b4"},"hatch_alpha":{"value":0.1},"line_alpha":{"value":0.1},"line_color":{"value":"#1f77b4"},"x":{"field":"x"},"y":{"field":"y"}},"id":"1216","type":"Circle"},{"attributes":{},"id":"1224","type":"AllLabels"},{"attributes":{"source":{"id":"1214"}},"id":"1219","type":"CDSView"},{"attributes":{},"id":"1200","type":"PanTool"},{"attributes":{"overlay":{"id":"1206"}},"id":"1202","type":"BoxZoomTool"},{"attributes":{},"id":"1203","type":"SaveTool"},{"attributes":{},"id":"1204","type":"ResetTool"},{"attributes":{"below":[{"id":"1192"}],"center":[{"id":"1195"},{"id":"1199"}],"left":[{"id":"1196"}],"renderers":[{"id":"1218"}],"title":{"id":"1220"},"toolbar":{"id":"1207"},"x_range":{"id":"1184"},"x_scale":{"id":"1188"},"y_range":{"id":"1186"},"y_scale":{"id":"1190"}},"id":"1183","subtype":"Figure","type":"Plot"},{"attributes":{},"id":"1228","type":"UnionRenderers"},{"attributes":{},"id":"1227","type":"AllLabels"},{"attributes":{},"id":"1186","type":"DataRange1d"},{"attributes":{"coordinates":null,"group":null},"id":"1220","type":"Title"},{"attributes":{},"id":"1188","type":"LinearScale"},{"attributes":{"coordinates":null,"formatter":{"id":"1226"},"group":null,"major_label_policy":{"id":"1227"},"ticker":{"id":"1193"}},"id":"1192","type":"LinearAxis"},{"attributes":{"coordinates":null,"formatter":{"id":"1223"},"group":null,"major_label_policy":{"id":"1224"},"ticker":{"id":"1197"}},"id":"1196","type":"LinearAxis"},{"attributes":{},"id":"1190","type":"LinearScale"},{"attributes":{},"id":"1205","type":"HelpTool"}],"root_ids":["1183"]},"title":"Bokeh Application","version":"2.4.3"}}
    </script>
    <script type="text/javascript">
      (function() {
        const fn = function() {
          Bokeh.safely(function() {
            (function(root) {
              function embed_document(root) {
              const docs_json = document.getElementById('1363').textContent;
              const render_items = [{"docid":"942b8d57-0079-4937-aaed-1fe8d4555acd","root_ids":["1183"],"roots":{"1183":"8c42557a-d72a-448d-8f4a-9f4cc7c0323b"}}];
              root.Bokeh.embed.embed_items(docs_json, render_items);
              }
              if (root.Bokeh !== undefined) {
                embed_document(root);
              } else {
                let attempts = 0;
                const timer = setInterval(function(root) {
                  if (root.Bokeh !== undefined) {
                    clearInterval(timer);
                    embed_document(root);
                  } else {
                    attempts++;
                    if (attempts > 100) {
                      clearInterval(timer);
                      console.log("Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing");
                    }
                  }
                }, 10, root)
              }
            })(window);
          });
        };
        if (document.readyState != "loading") fn();
        else document.addEventListener("DOMContentLoaded", fn);
      })();
    </script>
  </body>
</html>
</object>
#+end_export

Here's the actual HTML.

#+begin_src python output :exports both
print(html)
#+end_src

#+begin_src html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Full HTML</title>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.3.min.js"></script>
    <script type="text/javascript">
        Bokeh.set_log_level("info");
    </script>
  </head>
  <body>
    <div class="bk-root" id="8c42557a-d72a-448d-8f4a-9f4cc7c0323b" data-root-id="1183"></div>
  
    <script type="application/json" id="1363">
      {"942b8d57-0079-4937-aaed-1fe8d4555acd":{"defs":[],"roots":{"references":[{"attributes":{},"id":"1193","type":"BasicTicker"},{"attributes":{},"id":"1226","type":"BasicTickFormatter"},{"attributes":{"axis":{"id":"1192"},"coordinates":null,"group":null,"ticker":null},"id":"1195","type":"Grid"},{"attributes":{"bottom_units":"screen","coordinates":null,"fill_alpha":0.5,"fill_color":"lightgrey","group":null,"left_units":"screen","level":"overlay","line_alpha":1.0,"line_color":"black","line_dash":[4,4],"line_width":2,"right_units":"screen","syncable":false,"top_units":"screen"},"id":"1206","type":"BoxAnnotation"},{"attributes":{},"id":"1223","type":"BasicTickFormatter"},{"attributes":{"tools":[{"id":"1200"},{"id":"1201"},{"id":"1202"},{"id":"1203"},{"id":"1204"},{"id":"1205"}]},"id":"1207","type":"Toolbar"},{"attributes":{},"id":"1197","type":"BasicTicker"},{"attributes":{},"id":"1201","type":"WheelZoomTool"},{"attributes":{"data":{"x":[1,2],"y":[3,4]},"selected":{"id":"1229"},"selection_policy":{"id":"1228"}},"id":"1214","type":"ColumnDataSource"},{"attributes":{"coordinates":null,"data_source":{"id":"1214"},"glyph":{"id":"1215"},"group":null,"hover_glyph":null,"muted_glyph":{"id":"1217"},"nonselection_glyph":{"id":"1216"},"view":{"id":"1219"}},"id":"1218","type":"GlyphRenderer"},{"attributes":{"fill_color":{"value":"#1f77b4"},"line_color":{"value":"#1f77b4"},"x":{"field":"x"},"y":{"field":"y"}},"id":"1215","type":"Circle"},{"attributes":{},"id":"1229","type":"Selection"},{"attributes":{"fill_alpha":{"value":0.2},"fill_color":{"value":"#1f77b4"},"hatch_alpha":{"value":0.2},"line_alpha":{"value":0.2},"line_color":{"value":"#1f77b4"},"x":{"field":"x"},"y":{"field":"y"}},"id":"1217","type":"Circle"},{"attributes":{"axis":{"id":"1196"},"coordinates":null,"dimension":1,"group":null,"ticker":null},"id":"1199","type":"Grid"},{"attributes":{},"id":"1184","type":"DataRange1d"},{"attributes":{"fill_alpha":{"value":0.1},"fill_color":{"value":"#1f77b4"},"hatch_alpha":{"value":0.1},"line_alpha":{"value":0.1},"line_color":{"value":"#1f77b4"},"x":{"field":"x"},"y":{"field":"y"}},"id":"1216","type":"Circle"},{"attributes":{},"id":"1224","type":"AllLabels"},{"attributes":{"source":{"id":"1214"}},"id":"1219","type":"CDSView"},{"attributes":{},"id":"1200","type":"PanTool"},{"attributes":{"overlay":{"id":"1206"}},"id":"1202","type":"BoxZoomTool"},{"attributes":{},"id":"1203","type":"SaveTool"},{"attributes":{},"id":"1204","type":"ResetTool"},{"attributes":{"below":[{"id":"1192"}],"center":[{"id":"1195"},{"id":"1199"}],"left":[{"id":"1196"}],"renderers":[{"id":"1218"}],"title":{"id":"1220"},"toolbar":{"id":"1207"},"x_range":{"id":"1184"},"x_scale":{"id":"1188"},"y_range":{"id":"1186"},"y_scale":{"id":"1190"}},"id":"1183","subtype":"Figure","type":"Plot"},{"attributes":{},"id":"1228","type":"UnionRenderers"},{"attributes":{},"id":"1227","type":"AllLabels"},{"attributes":{},"id":"1186","type":"DataRange1d"},{"attributes":{"coordinates":null,"group":null},"id":"1220","type":"Title"},{"attributes":{},"id":"1188","type":"LinearScale"},{"attributes":{"coordinates":null,"formatter":{"id":"1226"},"group":null,"major_label_policy":{"id":"1227"},"ticker":{"id":"1193"}},"id":"1192","type":"LinearAxis"},{"attributes":{"coordinates":null,"formatter":{"id":"1223"},"group":null,"major_label_policy":{"id":"1224"},"ticker":{"id":"1197"}},"id":"1196","type":"LinearAxis"},{"attributes":{},"id":"1190","type":"LinearScale"},{"attributes":{},"id":"1205","type":"HelpTool"}],"root_ids":["1183"]},"title":"Bokeh Application","version":"2.4.3"}}
    </script>
    <script type="text/javascript">
      (function() {
        const fn = function() {
          Bokeh.safely(function() {
            (function(root) {
              function embed_document(root) {
              const docs_json = document.getElementById('1363').textContent;
              const render_items = [{"docid":"942b8d57-0079-4937-aaed-1fe8d4555acd","root_ids":["1183"],"roots":{"1183":"8c42557a-d72a-448d-8f4a-9f4cc7c0323b"}}];
              root.Bokeh.embed.embed_items(docs_json, render_items);
              }
              if (root.Bokeh !== undefined) {
                embed_document(root);
              } else {
                let attempts = 0;
                const timer = setInterval(function(root) {
                  if (root.Bokeh !== undefined) {
                    clearInterval(timer);
                    embed_document(root);
                  } else {
                    attempts++;
                    if (attempts > 100) {
                      clearInterval(timer);
                      console.log("Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing");
                    }
                  }
                }, 10, root)
              }
            })(window);
          });
        };
        if (document.readyState != "loading") fn();
        else document.addEventListener("DOMContentLoaded", fn);
      })();
    </script>
  </body>
</html>
#+end_src

#+begin_src python output :exports both
print(CDN)
#+end_src

#+RESULTS:
: <bokeh.resources.Resources object at 0x70ba4e97cd60>

* autoload_static

Using [[https://docs.bokeh.org/en/latest/docs/user_guide/output/embed.html#autoloading-scripts][~autoload_static~]] seems the closest to the way I'm loading javascript right now, and it won't require a nikola shortcode.

#+begin_src python :results none
from bokeh.embed import autoload_static

from graeae.visualization.altair_helpers import output_path

SLUG = "embedding-bokeh"

PATH = output_path(SLUG)
#+end_src

#+begin_src python output :exports both
FILE_NAME = "test-plot.js"

javascript, script_tag = autoload_static(plot, CDN, FILE_NAME)

print(script_tag)
#+end_src

#+RESULTS:
: <script src="test-plot.js" id="68045a2a-c90c-45f7-9f95-64c9c83399ba"></script>

The ~javascript~ variable now has a string with the HTML tags to define our plot so we need to save it to a file so that the ~src~ in the ~script~ tag is pointing to something taht the page can load.

#+begin_src python :results none
with (PATH/FILE_NAME).open("w") as writer:
    writer.write(javascript)
#+end_src

** Decomposing

#+begin_src python :results none
# pypi
from bs4 import BeautifulSoup
#+end_src

Sending the same figure to beautiful soup doesn't seem to reset the IDs so I'll make another one here to test out creating a document with a saved javascript file. Then I'll replace the body with the script-tag that I just created.

#+begin_src python output :exports both
re_plot = figure()
re_plot.circle([3, 4], [5, 6])
re_html = file_html(models=re_plot, resources=CDN, title="Re-Full HTML")
soup = BeautifulSoup(re_html, "html.parser")

soup.body.clear()
body = BeautifulSoup("<body>" + script_tag + "</body>")
soup.body.replace_with(body.body)
print(soup)
#+end_src

#+begin_src html
<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Re-Full HTML</title>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.3.min.js" type="text/javascript"></script>
<script type="text/javascript">
        Bokeh.set_log_level("info");
    </script>
</head>
<body><script id="befbff20-7c61-4db0-bb7b-f36edd0f3a00" src="test-plot.js"></script></body>
</html>
#+end_src

Now if we stick that HTML object into this post it should render the plot.

#+begin_src python output :exports both
objectify(soup)
#+end_src

#+begin_export html
<object type="text/html">
<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Re-Full HTML</title>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.3.min.js" type="text/javascript"></script>
<script type="text/javascript">
        Bokeh.set_log_level("info");
    </script>
</head>
<body><script id="befbff20-7c61-4db0-bb7b-f36edd0f3a00" src="test-plot.js"></script></body>
</html>
</object>
#+end_export

* Links
- Bokeh [Internet]. [cited 2024 Mar 26]. Web pages. Available from: https://docs.bokeh.org/en/latest/docs/user_guide/output/embed.html
