#+BEGIN_COMMENT
.. title: Embedding Bokeh
.. slug: embedding-bokeh
.. date: 2024-03-26 17:03:38 UTC-07:00
.. tags: experiment,bokeh,holoviews,hvplot
.. category: bokeh
.. link: 
.. description: Experimenting with embedding bokeh plots.
.. type: text

#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 3
#+PROPERTY: header-args :session ~/.local/share/jupyter/runtime/kernel-5e9f25eb-f65d-4208-9a9f-33f71e43652d-ssh.json

#+BEGIN_SRC python :results none :exports none
%load_ext autoreload
%autoreload 2
#+END_SRC

* Standalone HTML Pages

First, an example based on bokeh's documentation on [[https://docs.bokeh.org/en/latest/docs/user_guide/output/embed.html#html-files][creating standalone HTML files]].

** Imports and Setup

#+begin_src python :results none
# pypi
from bokeh.layouts import column
from bokeh.models import Div
from bokeh.plotting import figure
from bokeh.resources import CDN
from bokeh.embed import file_html
#+end_src

The [[https://docs.bokeh.org/en/latest/docs/reference/embed.html#bokeh.embed.file_html][~file_html~]] function will create the text for a standalone HTML file to show a bokeh figure ( f you just want to save the file they have a function called [[https://docs.bokeh.org/en/latest/docs/reference/io.html#bokeh.io.save][save]]). To get the plot into this post I'll put it in an ~<object>~ tag. To make things a little easier I'll make a function to do this.

#+begin_src python :results none
def objectify(html: str) -> None:
    """print html in object tags"""
    print('<object type="text/html" style="width:100%">')
    print(html)
    print('</object>')
    return
#+end_src

Now to create the plot.

#+begin_src python output :exports both
plot = figure(title = "Plot Title", sizing_mode="stretch_width")
plot.line(x=[1, 2, 3], y=[1, 4, 2])
div = Div(width_policy="max")

html = file_html(models= [div, plot], resources=CDN, title="HTML Title")

objectify(html)
#+end_src

#+RESULTS:
#+begin_export html
<object type="text/html" style="width:100%">
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>HTML Title</title>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.3.min.js"></script>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.4.3.min.js"></script>
    <script type="text/javascript">
        Bokeh.set_log_level("info");
    </script>
  </head>
  <body>
    <div class="bk-root" id="d7a4e912-af4c-442b-bf03-ce8eedb967e9" data-root-id="7395"></div>
  <div class="bk-root" id="7f8d3c87-ba7f-4004-9a63-9cc6f64e2476" data-root-id="7356"></div>
  
    <script type="application/json" id="7506">
      {"1d455afd-924e-46f7-85e1-c2e30a16f933":{"defs":[{"extends":null,"module":null,"name":"ReactiveHTML1","overrides":[],"properties":[]},{"extends":null,"module":null,"name":"FlexBox1","overrides":[],"properties":[{"default":"flex-start","kind":null,"name":"align_content"},{"default":"flex-start","kind":null,"name":"align_items"},{"default":"row","kind":null,"name":"flex_direction"},{"default":"wrap","kind":null,"name":"flex_wrap"},{"default":"flex-start","kind":null,"name":"justify_content"}]},{"extends":null,"module":null,"name":"GridStack1","overrides":[],"properties":[{"default":"warn","kind":null,"name":"mode"},{"default":null,"kind":null,"name":"ncols"},{"default":null,"kind":null,"name":"nrows"},{"default":true,"kind":null,"name":"allow_resize"},{"default":true,"kind":null,"name":"allow_drag"},{"default":[],"kind":null,"name":"state"}]},{"extends":null,"module":null,"name":"click1","overrides":[],"properties":[{"default":"","kind":null,"name":"terminal_output"},{"default":"","kind":null,"name":"debug_name"},{"default":0,"kind":null,"name":"clears"}]},{"extends":null,"module":null,"name":"NotificationAreaBase1","overrides":[],"properties":[{"default":"bottom-right","kind":null,"name":"position"},{"default":0,"kind":null,"name":"_clear"}]},{"extends":null,"module":null,"name":"NotificationArea1","overrides":[],"properties":[{"default":[],"kind":null,"name":"notifications"},{"default":"bottom-right","kind":null,"name":"position"},{"default":0,"kind":null,"name":"_clear"},{"default":[{"background":"#ffc107","icon":{"className":"fas fa-exclamation-triangle","color":"white","tagName":"i"},"type":"warning"},{"background":"#007bff","icon":{"className":"fas fa-info-circle","color":"white","tagName":"i"},"type":"info"}],"kind":null,"name":"types"}]},{"extends":null,"module":null,"name":"Notification","overrides":[],"properties":[{"default":null,"kind":null,"name":"background"},{"default":3000,"kind":null,"name":"duration"},{"default":null,"kind":null,"name":"icon"},{"default":"","kind":null,"name":"message"},{"default":null,"kind":null,"name":"notification_type"},{"default":false,"kind":null,"name":"_destroyed"}]},{"extends":null,"module":null,"name":"TemplateActions1","overrides":[],"properties":[{"default":0,"kind":null,"name":"open_modal"},{"default":0,"kind":null,"name":"close_modal"}]},{"extends":null,"module":null,"name":"MaterialTemplateActions1","overrides":[],"properties":[{"default":0,"kind":null,"name":"open_modal"},{"default":0,"kind":null,"name":"close_modal"}]}],"roots":{"references":[{"attributes":{},"id":"7375","type":"PanTool"},{"attributes":{"bottom_units":"screen","coordinates":null,"fill_alpha":0.5,"fill_color":"lightgrey","group":null,"left_units":"screen","level":"overlay","line_alpha":1.0,"line_color":"black","line_dash":[4,4],"line_width":2,"right_units":"screen","syncable":false,"top_units":"screen"},"id":"7381","type":"BoxAnnotation"},{"attributes":{},"id":"7376","type":"WheelZoomTool"},{"attributes":{"line_color":"#1f77b4","x":{"field":"x"},"y":{"field":"y"}},"id":"7390","type":"Line"},{"attributes":{},"id":"7379","type":"ResetTool"},{"attributes":{"axis":{"id":"7371"},"coordinates":null,"dimension":1,"group":null,"ticker":null},"id":"7374","type":"Grid"},{"attributes":{"line_alpha":0.2,"line_color":"#1f77b4","x":{"field":"x"},"y":{"field":"y"}},"id":"7392","type":"Line"},{"attributes":{"coordinates":null,"group":null,"text":"Plot Title"},"id":"7357","type":"Title"},{"attributes":{"axis":{"id":"7367"},"coordinates":null,"group":null,"ticker":null},"id":"7370","type":"Grid"},{"attributes":{"line_alpha":0.1,"line_color":"#1f77b4","x":{"field":"x"},"y":{"field":"y"}},"id":"7391","type":"Line"},{"attributes":{},"id":"7368","type":"BasicTicker"},{"attributes":{"coordinates":null,"formatter":{"id":"7398"},"group":null,"major_label_policy":{"id":"7399"},"ticker":{"id":"7372"}},"id":"7371","type":"LinearAxis"},{"attributes":{},"id":"7398","type":"BasicTickFormatter"},{"attributes":{},"id":"7359","type":"DataRange1d"},{"attributes":{},"id":"7372","type":"BasicTicker"},{"attributes":{},"id":"7363","type":"LinearScale"},{"attributes":{"width_policy":"max"},"id":"7395","type":"Div"},{"attributes":{"overlay":{"id":"7381"}},"id":"7377","type":"BoxZoomTool"},{"attributes":{"below":[{"id":"7367"}],"center":[{"id":"7370"},{"id":"7374"}],"left":[{"id":"7371"}],"renderers":[{"id":"7393"}],"sizing_mode":"stretch_width","title":{"id":"7357"},"toolbar":{"id":"7382"},"x_range":{"id":"7359"},"x_scale":{"id":"7363"},"y_range":{"id":"7361"},"y_scale":{"id":"7365"}},"id":"7356","subtype":"Figure","type":"Plot"},{"attributes":{},"id":"7403","type":"UnionRenderers"},{"attributes":{"coordinates":null,"data_source":{"id":"7389"},"glyph":{"id":"7390"},"group":null,"hover_glyph":null,"muted_glyph":{"id":"7392"},"nonselection_glyph":{"id":"7391"},"view":{"id":"7394"}},"id":"7393","type":"GlyphRenderer"},{"attributes":{"coordinates":null,"formatter":{"id":"7401"},"group":null,"major_label_policy":{"id":"7402"},"ticker":{"id":"7368"}},"id":"7367","type":"LinearAxis"},{"attributes":{},"id":"7378","type":"SaveTool"},{"attributes":{"source":{"id":"7389"}},"id":"7394","type":"CDSView"},{"attributes":{},"id":"7365","type":"LinearScale"},{"attributes":{},"id":"7399","type":"AllLabels"},{"attributes":{"tools":[{"id":"7375"},{"id":"7376"},{"id":"7377"},{"id":"7378"},{"id":"7379"},{"id":"7380"}]},"id":"7382","type":"Toolbar"},{"attributes":{"data":{"x":[1,2,3],"y":[1,4,2]},"selected":{"id":"7404"},"selection_policy":{"id":"7403"}},"id":"7389","type":"ColumnDataSource"},{"attributes":{},"id":"7380","type":"HelpTool"},{"attributes":{},"id":"7402","type":"AllLabels"},{"attributes":{},"id":"7404","type":"Selection"},{"attributes":{},"id":"7361","type":"DataRange1d"},{"attributes":{},"id":"7401","type":"BasicTickFormatter"}],"root_ids":["7395","7356"]},"title":"Bokeh Application","version":"2.4.3"}}
    </script>
    <script type="text/javascript">
      (function() {
        const fn = function() {
          Bokeh.safely(function() {
            (function(root) {
              function embed_document(root) {
              const docs_json = document.getElementById('7506').textContent;
              const render_items = [{"docid":"1d455afd-924e-46f7-85e1-c2e30a16f933","root_ids":["7395","7356"],"roots":{"7356":"7f8d3c87-ba7f-4004-9a63-9cc6f64e2476","7395":"d7a4e912-af4c-442b-bf03-ce8eedb967e9"}}];
              root.Bokeh.embed.embed_items(docs_json, render_items);
              }
              if (root.Bokeh !== undefined) {
                embed_document(root);
              } else {
                let attempts = 0;
                const timer = setInterval(function(root) {
                  if (root.Bokeh !== undefined) {
                    clearInterval(timer);
                    embed_document(root);
                  } else {
                    attempts++;
                    if (attempts > 100) {
                      clearInterval(timer);
                      console.log("Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing");
                    }
                  }
                }, 10, root)
              }
            })(window);
          });
        };
        if (document.readyState != "loading") fn();
        else document.addEventListener("DOMContentLoaded", fn);
      })();
    </script>
  </body>
</html>
</object>
#+end_export

Note the ~Div~ in there to set the ~width_policy~ to "max". It was the only way I could figure out to get the figure as wide as the column. I couldn't get the height exactly right - here's another area to investigate.

I made the "title" arguments a little weird because when I first made the plot I got the two arguments confused. They're both called title but one gives a title to the plot (the figure argument) and one puts it in ~<title>~ tags (the ~file_html~ function). Here's what the actual HTML looks like.

#+begin_src python output :exports both
print(html)
#+end_src

#+RESULTS:
#+begin_src html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>HTML Title</title>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.3.min.js"></script>
    <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.4.3.min.js"></script>
    <script type="text/javascript">
        Bokeh.set_log_level("info");
    </script>
  </head>
  <body>
    <div class="bk-root" id="37e54b61-cb10-4e87-a14e-f33f9a9c9542" data-root-id="6758"></div>
  <div class="bk-root" id="c7d6a897-3c74-412a-ac9c-b7a6357aac5d" data-root-id="6719"></div>
  
    <script type="application/json" id="6869">
      {"0b7e4c40-d195-4444-80df-f70d49a927fe":{"defs":[{"extends":null,"module":null,"name":"ReactiveHTML1","overrides":[],"properties":[]},{"extends":null,"module":null,"name":"FlexBox1","overrides":[],"properties":[{"default":"flex-start","kind":null,"name":"align_content"},{"default":"flex-start","kind":null,"name":"align_items"},{"default":"row","kind":null,"name":"flex_direction"},{"default":"wrap","kind":null,"name":"flex_wrap"},{"default":"flex-start","kind":null,"name":"justify_content"}]},{"extends":null,"module":null,"name":"GridStack1","overrides":[],"properties":[{"default":"warn","kind":null,"name":"mode"},{"default":null,"kind":null,"name":"ncols"},{"default":null,"kind":null,"name":"nrows"},{"default":true,"kind":null,"name":"allow_resize"},{"default":true,"kind":null,"name":"allow_drag"},{"default":[],"kind":null,"name":"state"}]},{"extends":null,"module":null,"name":"click1","overrides":[],"properties":[{"default":"","kind":null,"name":"terminal_output"},{"default":"","kind":null,"name":"debug_name"},{"default":0,"kind":null,"name":"clears"}]},{"extends":null,"module":null,"name":"NotificationAreaBase1","overrides":[],"properties":[{"default":"bottom-right","kind":null,"name":"position"},{"default":0,"kind":null,"name":"_clear"}]},{"extends":null,"module":null,"name":"NotificationArea1","overrides":[],"properties":[{"default":[],"kind":null,"name":"notifications"},{"default":"bottom-right","kind":null,"name":"position"},{"default":0,"kind":null,"name":"_clear"},{"default":[{"background":"#ffc107","icon":{"className":"fas fa-exclamation-triangle","color":"white","tagName":"i"},"type":"warning"},{"background":"#007bff","icon":{"className":"fas fa-info-circle","color":"white","tagName":"i"},"type":"info"}],"kind":null,"name":"types"}]},{"extends":null,"module":null,"name":"Notification","overrides":[],"properties":[{"default":null,"kind":null,"name":"background"},{"default":3000,"kind":null,"name":"duration"},{"default":null,"kind":null,"name":"icon"},{"default":"","kind":null,"name":"message"},{"default":null,"kind":null,"name":"notification_type"},{"default":false,"kind":null,"name":"_destroyed"}]},{"extends":null,"module":null,"name":"TemplateActions1","overrides":[],"properties":[{"default":0,"kind":null,"name":"open_modal"},{"default":0,"kind":null,"name":"close_modal"}]},{"extends":null,"module":null,"name":"MaterialTemplateActions1","overrides":[],"properties":[{"default":0,"kind":null,"name":"open_modal"},{"default":0,"kind":null,"name":"close_modal"}]}],"roots":{"references":[{"attributes":{},"id":"6739","type":"WheelZoomTool"},{"attributes":{"data":{"x":[1,2,3],"y":[1,4,2]},"selected":{"id":"6767"},"selection_policy":{"id":"6766"}},"id":"6752","type":"ColumnDataSource"},{"attributes":{},"id":"6761","type":"BasicTickFormatter"},{"attributes":{},"id":"6738","type":"PanTool"},{"attributes":{"width_policy":"max"},"id":"6758","type":"Div"},{"attributes":{},"id":"6762","type":"AllLabels"},{"attributes":{},"id":"6764","type":"BasicTickFormatter"},{"attributes":{},"id":"6765","type":"AllLabels"},{"attributes":{},"id":"6731","type":"BasicTicker"},{"attributes":{"source":{"id":"6752"}},"id":"6757","type":"CDSView"},{"attributes":{"coordinates":null,"group":null,"text":"Plot Title"},"id":"6720","type":"Title"},{"attributes":{"axis":{"id":"6734"},"coordinates":null,"dimension":1,"group":null,"ticker":null},"id":"6737","type":"Grid"},{"attributes":{},"id":"6722","type":"DataRange1d"},{"attributes":{"line_color":"#1f77b4","x":{"field":"x"},"y":{"field":"y"}},"id":"6753","type":"Line"},{"attributes":{"tools":[{"id":"6738"},{"id":"6739"},{"id":"6740"},{"id":"6741"},{"id":"6742"},{"id":"6743"}]},"id":"6745","type":"Toolbar"},{"attributes":{},"id":"6726","type":"LinearScale"},{"attributes":{"line_alpha":0.1,"line_color":"#1f77b4","x":{"field":"x"},"y":{"field":"y"}},"id":"6754","type":"Line"},{"attributes":{},"id":"6728","type":"LinearScale"},{"attributes":{"line_alpha":0.2,"line_color":"#1f77b4","x":{"field":"x"},"y":{"field":"y"}},"id":"6755","type":"Line"},{"attributes":{"below":[{"id":"6730"}],"center":[{"id":"6733"},{"id":"6737"}],"left":[{"id":"6734"}],"renderers":[{"id":"6756"}],"sizing_mode":"stretch_width","title":{"id":"6720"},"toolbar":{"id":"6745"},"x_range":{"id":"6722"},"x_scale":{"id":"6726"},"y_range":{"id":"6724"},"y_scale":{"id":"6728"}},"id":"6719","subtype":"Figure","type":"Plot"},{"attributes":{"coordinates":null,"formatter":{"id":"6761"},"group":null,"major_label_policy":{"id":"6762"},"ticker":{"id":"6735"}},"id":"6734","type":"LinearAxis"},{"attributes":{},"id":"6766","type":"UnionRenderers"},{"attributes":{},"id":"6767","type":"Selection"},{"attributes":{"bottom_units":"screen","coordinates":null,"fill_alpha":0.5,"fill_color":"lightgrey","group":null,"left_units":"screen","level":"overlay","line_alpha":1.0,"line_color":"black","line_dash":[4,4],"line_width":2,"right_units":"screen","syncable":false,"top_units":"screen"},"id":"6744","type":"BoxAnnotation"},{"attributes":{"coordinates":null,"data_source":{"id":"6752"},"glyph":{"id":"6753"},"group":null,"hover_glyph":null,"muted_glyph":{"id":"6755"},"nonselection_glyph":{"id":"6754"},"view":{"id":"6757"}},"id":"6756","type":"GlyphRenderer"},{"attributes":{"coordinates":null,"formatter":{"id":"6764"},"group":null,"major_label_policy":{"id":"6765"},"ticker":{"id":"6731"}},"id":"6730","type":"LinearAxis"},{"attributes":{},"id":"6742","type":"ResetTool"},{"attributes":{"overlay":{"id":"6744"}},"id":"6740","type":"BoxZoomTool"},{"attributes":{},"id":"6741","type":"SaveTool"},{"attributes":{"axis":{"id":"6730"},"coordinates":null,"group":null,"ticker":null},"id":"6733","type":"Grid"},{"attributes":{},"id":"6743","type":"HelpTool"},{"attributes":{},"id":"6724","type":"DataRange1d"},{"attributes":{},"id":"6735","type":"BasicTicker"}],"root_ids":["6758","6719"]},"title":"Bokeh Application","version":"2.4.3"}}
    </script>
    <script type="text/javascript">
      (function() {
        const fn = function() {
          Bokeh.safely(function() {
            (function(root) {
              function embed_document(root) {
              const docs_json = document.getElementById('6869').textContent;
              const render_items = [{"docid":"0b7e4c40-d195-4444-80df-f70d49a927fe","root_ids":["6758","6719"],"roots":{"6719":"c7d6a897-3c74-412a-ac9c-b7a6357aac5d","6758":"37e54b61-cb10-4e87-a14e-f33f9a9c9542"}}];
              root.Bokeh.embed.embed_items(docs_json, render_items);
              }
              if (root.Bokeh !== undefined) {
                embed_document(root);
              } else {
                let attempts = 0;
                const timer = setInterval(function(root) {
                  if (root.Bokeh !== undefined) {
                    clearInterval(timer);
                    embed_document(root);
                  } else {
                    attempts++;
                    if (attempts > 100) {
                      clearInterval(timer);
                      console.log("Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing");
                    }
                  }
                }, 10, root)
              }
            })(window);
          });
        };
        if (document.readyState != "loading") fn();
        else document.addEventListener("DOMContentLoaded", fn);
      })();
    </script>
  </body>
</html>
#+end_src

#+RESULTS:
: <bokeh.resources.Resources object at 0x70ba4e97cd60>

I had thought that maybe the ~CDN~ argument was a string but it's actually an object.

* autoload_static

Using [[https://docs.bokeh.org/en/latest/docs/user_guide/output/embed.html#autoloading-scripts][~autoload_static~]] lets you save the javascript to a file and then load it into the page using a ~<script>~ tag.

#+begin_notecard
**Note:** This is what graeae's ~EmbedBokeh~ uses. ~EmbedHoloviews~ uses ~holoviews.save~.
#+end_notecard

#+begin_src python :results none
from bokeh.embed import autoload_static
#+end_src

I'm going to use some code from this project to make setting up the javascript file a little easier.
#+begin_src python :results none
from graeae.visualization.altair_helpers import output_path

SLUG = "embedding-bokeh"

PATH = output_path(SLUG)
#+end_src


#+begin_src python output :exports both
FILE_NAME = "test-plot.js"

re_plot = figure(title = "Plot Title", sizing_mode="stretch_width")
re_plot.line(x=[1, 2, 3], y=[4, 1, 2])

javascript, script_tag = autoload_static(re_plot, CDN, FILE_NAME)

print(script_tag)
#+end_src

#+RESULTS:
: <script src="test-plot.js" id="af99effb-d79b-4f6e-84aa-0af5e1a98d54"></script>

#+begin_notecard
**Note:** I originally created this with a div and plot, which required me to make a new plot or the ~autoload_static~ function threw an error (probably because I was re-using the Div ID), but passing in the DIV didn't help the styling any so I took it back out.
#+end_notecard

The ~javascript~ variable now has a string with the HTML tags to define our plot so we need to save it to a file so that the ~src~ in the ~script~ tag is pointing to something taht the page can load.

#+begin_src python :results none
with (PATH/FILE_NAME).open("w") as writer:
    writer.write(javascript)
#+end_src

** Decomposing

Since the ~autoload_static~ function only creates a javascript file we'll need to add some HTML to get bokeh into the document. Ultimately I'll try and get it into the header of the post that's using it, but for now I'll stick to keeping the plots inside standalone HTML objects. So, to get the document structure I'll re-use the HTML from the previous plot and stick the script tag into it.

I'll use [[https://beautiful-soup-4.readthedocs.io/en/latest/][Beautiful Soup]] to manipulate the HTML.

#+begin_src python :results none
# pypi
from bs4 import BeautifulSoup
#+end_src

#+begin_src python :results none
soup = BeautifulSoup(html, "html.parser")
#+end_src

#+begin_src python output :exports both
soup.body.clear()
scripted = BeautifulSoup("<body>"
                         + script_tag
                         + "</body>")
soup.body.replace_with(scripted.body)
print(soup)
#+end_src

#+RESULTS:
#+begin_src html
<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>HTML Title</title>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.3.min.js" type="text/javascript"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.4.3.min.js" type="text/javascript"></script>
<script type="text/javascript">
        Bokeh.set_log_level("info");
    </script>
</head>
<body><script id="af99effb-d79b-4f6e-84aa-0af5e1a98d54" src="test-plot.js"></script></body>
</html>
#+end_src

Now if we stick that HTML object into this post it should render the plot.

#+begin_src python output :exports both
objectify(soup)
#+end_src

#+RESULTS:
#+begin_export html
<object type="text/html" style="width:100%">
<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
<title>HTML Title</title>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.4.3.min.js" type="text/javascript"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.4.3.min.js" type="text/javascript"></script>
<script type="text/javascript">
        Bokeh.set_log_level("info");
    </script>
</head>
<body><script id="af99effb-d79b-4f6e-84aa-0af5e1a98d54" src="test-plot.js"></script></body>
</html>
</object>
#+end_export

Well, the width didn't work, so if this is the way to go then I need to figure out the right way to get bokeh to change what it's doing. Also note that the ~<head>~ is importing both bokeh and its widgets (without the column and div it doesn't import the widgets).

Next up, the ~components~ function.

* Components

* Links
- Beautiful Soup Documentation — Beautiful Soup 4.4.0 documentation [Internet]. [cited 2024 Mar 27]. Available from: https://beautiful-soup-4.readthedocs.io/en/latest/
- Bokeh [Internet]. [cited 2024 Mar 26]. Web pages. Available from: https://docs.bokeh.org/en/latest/docs/user_guide/output/embed.html
