#+TITLE: Altair Helpers

#+begin_src python :tangle altair_helpers.py
<<imports>>

<<javascript-saving-constants>>

<<nikola-shortcode>>

<<output-path>>


<<print-table>>


<<save-chart>>

<<save-chart-javascript>>
#+end_src

* Imports

#+begin_src python :noweb-ref imports
# python
from functools import partial
from pathlib import Path
from string import Template

# pypi
from tabulate import tabulate

import altair
import pandas
#+end_src

* Output Path

#+begin_src python :noweb-ref output-path
def output_path(slug: str, path_prefix: str="../files/posts/") -> Path:
    """Setup the Folder path for posts

    Args:
     slug: the slug for the post

    Returns:
     path object for output folder
    """
    OUTPUT_PATH = Path(f"{path_prefix}{slug}")
    if not OUTPUT_PATH.is_dir():
        OUTPUT_PATH.mkdir()
    return OUTPUT_PATH
#+end_src

* Print Table

#+begin_src python :noweb-ref print-table
TABLE = partial(tabulate, tablefmt="orgtbl",
                showindex=False,
                headers="keys")

def print_org_table(frame: pandas.DataFrame) -> None:
    """Use tabulate to print a table

    Args:
     frame: the data frame to print
    """
    print(TABLE(frame))
    return
#+end_src

* Save Chart

#+begin_src python :noweb-ref save-chart
def save_chart(chart: altair.Chart, name: str,
               output_path: Path,
               height: int=600) -> None:
    """Save and print the altair chart HTML tag

    This saves an entire HTML document (head and body) so it needs
    to be embedded as an <object>

    Args:
     chart: altair chart to save
     name: name of the chart to use (with or without file extension)
     output:path: folder-path for the output file
     height: argument to give the html block for height

    Side-Effect:
     prints the HTML export block for the chart
    """
    name = name if name.endswith(".html") else f"{name}.html"
    chart.save(str(output_path/name))

    print(f"""#+begin_export html
<object type="text/html" data="{name}" style="width:100%" height={height}>
  <p>Figure Missing</p>
</object>
,#+end_export""")
    return
#+end_src

* Save Chart as Javascript

This saves the chart as a javascript function, so it needs to be included as a ~<script>~ and to have a ~<div>~ that it can use as a target to stick the chart into.

** The Javascript Template
This is based on the output given by the ~Chart.save~ method (used in the ~save_chart~ function above).

#+begin_src python :noweb-ref javascript-saving-constants
VEGA_EMBED_TEMPLATE = Template("""
     (function(vegaEmbed) {
       var spec = $JSON_SPEC;

      var embedOpt = {"mode": "vega-lite"};

      function showError(el, error){
          el.innerHTML = ('<div class="error" style="color:red;">'
                          + '<p>JavaScript Error: ' + error.message + '</p>'
                          + "<p>This usually means there's a typo in your chart specification. "
                          + "See the javascript console for the full traceback.</p>"
                          + '</div>');
          throw error;
      } // showError
      const el = document.getElementById('$DIV_ID');
      vegaEmbed("#$DIV_ID", spec, embedOpt)
        .catch(error => showError(el, error));
    })(vegaEmbed);
""")
#+end_src

** The Nikola Shortcode

This is a template for the string to emit once the javascript is saved. It is a nikola shortcode that's being created elsewhere (probably Beach Pig Thigh).

#+begin_src python :noweb-ref nikola-shortcode
SHORTCODE = Template('{{% altairdiv source="$SOURCE" divid="$DIVID" %}}')
#+end_src

This is going to require two arguments to complet.

 - ~SOURCE~ is the name of the javascript file that has the code for vega-embed
 - ~DIVID~ is the ID of the HTML ~<div>~ that vega-embed is going to stick the chart into
   
** The Save Vega Embed Javascript Function

#+begin_src python :noweb-ref save-chart-javascript
def save_vega_embed(chart: altair.Chart,
                    name: str,
                    output_path: Path,
                    div_id: str,
                    json_indent: int=None,
                    emit: bool=True) -> Path:
    """Save the vega chart as a javascript file

    This will require that there's a <div> target for the chart and
    a <script> tag to load the file we're going to save

    Params:

     - `chart`: altair chart to get the JSON spec from
     - `name`: name to save the javascript file to
     - `output_path`: path object to open the file
     - `div_id`: ID of the div tag to hold the chart
     - `json_indent`: amount json.dumps should indent to pretty-print the spec
     - `emit`: if True, print the shortcode
    Returns:
     path to the saved javascript
    """
    SUFFIX = ".js"
    file_name = name if name.endswith(SUFFIX) else name + SUFFIX
    javascript = VEGA_EMBED_TEMPLATE.substitute(
        JSON_SPEC=chart.to_json(indent=json_indent),
        DIV_ID=div_id
    )

    file_path = output_path/file_name
    with (file_path).open("w") as writer:
        writer.write(javascript)

    if emit:
        print(SHORTCODE.substitute(SOURCE=file_name, DIVID=div_id))
    return file_path
#+end_src
